## PN_choose_model_100.ipynb
Зафиксировано число тем = 100. Были поробованы разные модели, отобрано несколько моделей: 
* без регуляризатора
 * name = model_100_1, n_topics = 100, n_doc_passes = 5, seed_value = 100, n_iterations = 20, n_top_tokens = 15, p_threshold = 0.25
 * last_perplexity_score = 1065.4691168
 * last_sparsity_phi_score = 0.76290761491
 * last_sparsity_theta_score = 0.00162797446315
 * last_topic_kernel_avgsize = 155.89
 * last_topic_kernel_purity = 0.287688379533
 * last_topic_kernel_contrast = 0.468397835486
* с регуляризаторами, хорошие показатели, но avg kernel size = 90
 * name = model_100_7, n_topics = 100, n_doc_passes = 5, seed_value = 100, n_iterations = 20, n_top_tokens = 15, p_threshold = 0.25, ss_theta_regularizer, tau = -0.5, decorrelator_phi_regularizer, tau = 10, ss_phi_regularizer, tau = -0.5
 * last_perplexity_score = 886.578272434
 * last_sparsity_phi_score = 0.979305968443
 * last_sparsity_theta_score = 0.769207777133
 * last_topic_kernel_avgsize = 89.23
 * last_topic_kernel_purity = 0.50039540324
 * last_topic_kernel_contrast = 0.728560167745
* с регуляризаторами, хорошие показатели, примерно одинаковые, avg kernel size = 24
 * name = model_100_12, n_topics = 100, n_doc_passes = 5, seed_value = 100, n_iterations = 20, n_top_tokens = 15, p_threshold = 0.25, ss_theta_regularizer, tau = -0.5, decorrelator_phi_regularizer, tau = 10, ss_phi_regularizer, tau = -2
 * last_perplexity_score = 384.451799322
 * last_sparsity_phi_score = 0.994879373428
 * last_sparsity_theta_score = 0.74879280325
 * last_topic_kernel_avgsize = 23.68
 * last_topic_kernel_purity = 0.629848034538
 * last_topic_kernel_contrast = 0.776075642

## PN_visualize_convex_hull_100_3models.ipynb
Для выбранных моделей были посчитаны внутренние расстояния, посчитан функционал opt при выбрасывании одной темы.

Выводы: самая отрегуляризованная модель (3) расстояние наибольшее, модель 1 - размазано расстояние.

TODO: сравнить метрики расстояния
## PN_model_to_ndw.ipynb
Для 3х моделей.

TODO: сравнить sample model без умножения на длину документа.
## PN_ndw_to_batch.ipynb
Для 3х моделей.

## TODO
Для каждого из созданного датасета:
* создать несколько моделей, сравнить их (для начала можно выбрать 2 модели - без регуляризаторов и сильно разреженную)
* стабильность: запустить много раз, посмотреть сколько новых тем с каждым разом; как определить новая ли тема? (перестановки и т.д) -> строим матрицу попарных расстояний (hemm) и по топ словам, пытаемся соотнести - порог, новая/не новая + почитать статьи
* полнота: запускаем один раз, строим попарные расстояния внутренние, запускаем оптимизацию, смотрим расстояния, откидываем зависимые

## PN_choose_model_20_sample-model123.ipynb
Даже без регуляризаторов модели получаются с норм показателями (кроме ss theta и большой средний размер ядра) 


todo: для каждой получившейся convex hull посчитать внутреннее расстояние и спроектировать на original
## PN_build_convex_hull-sample_m3_2
Модель 3: 
* name = model_100_12, n_topics = 100, n_doc_passes = 5, seed_value = 100, n_iterations = 20, n_top_tokens = 15, p_threshold = 0.25, ss_theta_regularizer, tau = -0.5, decorrelator_phi_regularizer, tau = 10, ss_phi_regularizer, tau = -2

Сonvex hulls:
- create_model_fn_1: n_topics=20, n_doc_passes=5, seed_value=100 + n_iteration, n_top_tokens=15, p_mass_threshold=0.25
От порога зависит сколько тем получится в convex hull, для модели из 20 тем 0,6 слишком большой - остаётся 24 темы (2.30h); или 25-30 тем уже на 20 итерации (10m) и потом число тем колеблится +/- в этих рамках, итого 28 тем(1.30h)
Порог 0.4: за 40 итераций постоянно растёт convex hull, итого 150 тем
Порог 0.5: за 60 итераций дошло до 61
Порог 0.45:

- create_model_fn_2: n_topics=100, n_doc_passes=5, seed_value=100 + n_iteration, n_top_tokens=15, p_mass_threshold=0.25
Delayed Filtering each 10: накапливалось и отфильтровывалось до 100-110, итого 40 итераций 112 тем (2h)
Filtering: 100-120 число тем, итого 50 итераций 111 тем (2h)
- create_model_fn_3: n_topics=20, n_doc_passes=5, seed_value=100 + n_iteration, n_top_tokens=15, p_mass_threshold=0.25, ['decorrelator_phi_regularizer'].tau = 300, ['ss_theta_regularizer'].tau = -5, ['ss_phi_regularizer'].tau = -20
Delayed Filtering: сошлась до 56 тем (3h)
Filtering: после 60 итерации (1h) сошлась к 57 темам (3.30h)
- create_model_fn_4: n_topics=100, n_doc_passes=5, seed_value=100 + n_iteration, n_top_tokens=15, p_mass_threshold=0.25, ['decorrelator_phi_regularizer'].tau = 10, ['ss_theta_regularizer'].tau = -0.5, ['ss_phi_regularizer'].tau = -2
Delayed Filtering each 10: 233, 326, 410, 484
Filtering: 
Порог 0.6: 543 и всё растёт, для такой хорошей модели порог нужно выше задавать
Порог 0.7: отфильтровка до 304 
Порог 0.8: отфильтровка до 139 / набор до 118

По opt res до original convex hull 21, 22, 31 ближе всего -> 1 и 3 модели (+ там меньше тем)
То есть модели из 20 тем 

- порог 
- оценка качества: 
* стабильности
* полноты 


# TODO
* сравнить с opt Вовы + 
* подобрать гранулярность +(
* написать complex reg + 
* попробовать: когда строить convex hull хранить ещё и все отфильтрованные темы, при добавлении новых тем добавлять и убранные до этого и заново запускать фильтр +


In [1]:
# ('phi_original', 59.75)

Model1, different th, 200 iterations, wf:
 
|  th | n_topics |  opt_to_orig  | gran | x_count_mean |
|:---:|:--------:|:-------------:|:----:|:------------:|
| 0.4 |    175   |  0.2-0.3-0.35 |  131 |     3.36     |
| 0.5 |   50-60  |  0.2-0.33-0.4 |  126 |     3.28     |
| 0.6 |   26-30  |  0.2-0.28-0.4 |  128 |      3.3     |
| 0.7 |   17-22  |  0.2-0.33-0.4 |  132 |     3.76     |
| 0.8 |   9-13   |  0.2-0.33-0.4 |  114 |     3.36     |
| 0.9 |    3-6   | 0.23-0.3-0.33 |  90  |      2.6     |

Model1, different th, 150 iterations, df:
* 0.4
 * n_topics: 190
 * opt_to_orig: 0.2-0.3-0.4
 * gran: 131
 * 3.36
* 0.6
 * 22
 * 0.22-0.35
 * 122
 * 3
* 0.8
 * 12
 * .23 -0.38
 * 109
 * 2.89

* wh, df одинаковый результат (200it: 4,30; 2;    150: 3,00; 3,00)
* gran, of course, the same
* x_count_mean, of course, +- the same
* как порог выбрать?
 
20 topics, Different regs, 0.6, 100 iterations:
* ('phi_convex_hull_wf_m_reg2_1', (-5,-5,-)
 * n_topics: 55 (mb not sosh)
 * opt_to_orig: 0.3-0.45-0.6
 * gran: 51.754716981132077)
 * x_count_mean: 2.16
* ('phi_convex_hull_wf_m_reg3_1', (-10,-10,-)
 * 55 (mb not sosh)
 * 0.4-0.65-0.8
 * 48.145454545454548)
 * 0.6
* ('phi_convex_hull_wf_m_reg4_1', (-5,-5,-10)
 * 55 (mb not sosh)
 * 0.3-0.45-0.6
 * 54.169811320754718)
 * 2.32
* ох, получается, что модель, которая хорошо выражается через 1-2 темы - самая отдаленная
* добавление decor с -10 не сильно меняет что-то

10 topics
* 0.6
 * 10 - 16
 * 0.2-0.35
 * 215
 * 7.69
* 0.8
 * 4 - 6
 * 0.22-0.32
 * 191
 * 7
* чем больше гран, чем общнее темы - тем ближе проектируется, но выражается чем больше тем

## algo (?)
* df
 * много раз запускается построение модели, запоминаются темы 
 * __запускается фильтрация__:
 * каждая тема пытается спроектироваться на матрицу всех тем (opt: не на все, а на N_CLOSEST_TOPICS(=15?)) - текущая тема
 * выбираются все темы, opt_distance < threshold, сортируются по opt_distance = candidates
 * набираются topics_to_remove: тема из candidates + _не близка_ ни к какой теме, которая уже в topics_to_remove
 *  _не близка_ t1, t2: 
   * по порогу
   * distances от t1 до каждой другой темы, сортируем, берем N_CLOSEST_TOPICS - если рассматриваемая тема t2 там есть -> близка
 * __пока |topics_to_remove| = 0__

* wf
 * то же самое, только фильтеринг после каждой новой построенной модели, а не в конце

### qa
* algo адекватный?
* что с threshold делать?
* чем больше гран, чем общнее темы - тем ближе проектируется, но выражается чем больше тем
* близость её как определять
* distance - hungarian alg of matching ? 
* стабильность и полнота; метрика

* Разработка графовых методов анализа структурированных финансовых данных.

### todo
* реализовать поиск коэффициентов с помощью разложения
* тесты +
 * фи, перестановка столбцов +
 * фи, выпуклая комбинация с рандомными весами +
* написать письмо о единственности 
* формализовать метрики стабильности
* формализовать метрики полноты
* добиться с помощью регул. x_count_mean = 0 (+1)
* переделать gran: mean -> mean + hist
* расстояние kl

original set немного странные темы? (первое слово топ-топ, остальные слишком маленькие)
работа          0.164683
статья          0.096539
автор           0.078489
журнал          0.074716
исследование    0.050769
публикация      0.039446
раздел          0.032632
тема            0.032347
вопрос          0.022783
коллега         0.021196
монография      0.019547
материал        0.018971
постнаука       0.016101
редактор        0.014917
название        0.014868

* 0.4 
 * n_topics: 175 topics (50 it)
 * opt_to_orig: 0.2-0.3-0.35
 * gran: 131
 * x_count_mean: 3.36 
* 0.5 
 * 50-60 topics (strange down on 75 it)
 * 0.2-0.33-0.4
 * 126
 * 3.28
* 0.6 
 * 26-30 (> 25 it)
 * 0.2-0.28-0.4
 * 128
 * 3.33
* 0.7 
 * 17-22 (> 10 it)
 * 0.2-0.33-0.4
 * 132
 * 3.76
* 0.8 
 * 9-13 (> 10 it)
 * 0.2-0.33-0.4
 * 114
 * 3.36
* 0.9 
 * 3-6 (> 10 it)
 * 0.23-0.3-0.33
 * 90
 * 2.6

In [4]:
import numpy as np
n_dw_test = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 0.0], [7.0, 8.0, 9.0], [10.0, 0.0, 12.0]])

Phi_test_init = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]])
Theta_test_init = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]);

Phi_test_init = Phi_test_init / np.sum(Phi_test_init, 0)
Theta_test_init = Theta_test_init / np.sum(Theta_test_init, 0)

In [5]:
Phi_test_init

array([[ 0.0625,  0.1   ],
       [ 0.1875,  0.2   ],
       [ 0.3125,  0.3   ],
       [ 0.4375,  0.4   ]])

In [6]:
Theta_test_init

array([[ 0.2       ,  0.28571429,  0.33333333],
       [ 0.8       ,  0.71428571,  0.66666667]])

In [7]:
Phi_test_init.dot(Theta_test_init)

array([[ 0.0925    ,  0.08928571,  0.0875    ],
       [ 0.1975    ,  0.19642857,  0.19583333],
       [ 0.3025    ,  0.30357143,  0.30416667],
       [ 0.4075    ,  0.41071429,  0.4125    ]])

In [8]:
n_dw_test

array([[  1.,   2.,   3.],
       [  4.,   5.,   0.],
       [  7.,   8.,   9.],
       [ 10.,   0.,  12.]])

* Разобраться в письмах
* Написать issue по transform
* Написать one to one matching - хотим же найти такие же
* написать em + не все колонки
* проанализировать notebooks
* запустить на ночь

* написать уже метрики
 * по стабильности
 * по полноте
* проанализировать результаты